### ISSUE TITLE
Remove scalar indexing on `AbstractExpr`'s from atom formulation

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/Convex.jl#614]
As shown by #613 & #254 this leads to huge performance cliffs. Here is an audit of such issues in our current atoms:

### ExponentialCone based issues

- [x] ExpAtom (fixed by #613): https://github.com/jump-dev/Convex.jl/blob/2a3b5202549d5c442bdafce01f157e5c168e3476/src/atoms/ExpAtom.jl#L37
- [x] EntropyAtom (fixed by #618): https://github.com/jump-dev/Convex.jl/blob/18d378ecfe1e2cbad31eacdc2378d41019659301/src/atoms/EntropyAtom.jl#L43
- [x] LogAtom (fixed by #618): https://github.com/jump-dev/Convex.jl/blob/18d378ecfe1e2cbad31eacdc2378d41019659301/src/atoms/LogAtom.jl#L37

These could all be handled just like #613. Perhaps we can find a way to reuse the code here rather than inlining near-identical implementations.

### Other cases
- [x] AbsAtom in the complex case (fixed by #619): https://github.com/jump-dev/Convex.jl/blob/18d378ecfe1e2cbad31eacdc2378d41019659301/src/atoms/AbsAtom.jl#L28
- [x] GeoMeanAtom #621: https://github.com/jump-dev/Convex.jl/blob/18d378ecfe1e2cbad31eacdc2378d41019659301/src/atoms/GeoMeanAtom.jl#L43
- [x] QolElemAtom #620: https://github.com/jump-dev/Convex.jl/blob/18d378ecfe1e2cbad31eacdc2378d41019659301/src/atoms/QolElemAtom.jl#L37

**Comment by ericphanson** [comment]
🎉
